#with root, package and instruction level overlays
config: $_defs.
_vars:
  middleware:
    preauths: &middleware_preauth
     - com.xyz.createSpan:
    finally: &middleware_finally
      - com.xyz.endSpan:
  validation:
export:
  com:
    abc:
      preauths:
        - *middleware_preauth
        - com.abc.custom_fn:
          args:
          on_error:
            - com.xyz.gs.retry:
              args:
                num_retry: 3
      finally: *middleware_finally
      validation: 
          push:
            - com.abc.validateCreateUserArgs:
            
            
# config:
# fragments:
#   email_fragment:
#     sender: admin@xyz.com
#     templateName: sendgrid_wrong_login_attempt_template
#     to: "*gs_actor.email"
# middleware:
#   preAuths:
#    com.xyz.createSpan:
  
#   finally:
#    com.xyz.endSpan:
#   com:
#    xyz:
#     helloWorld:
#       auths:
#         push:
#         - com.xyz.sendEmail:
#           args: "*fragments.email_fragment"
#           on_error:
#             - com.xyz.gs.retry:
#                 args:
#                   num_retry: 3
#                 on_error:
#                   - com.xyz.email_backlog:
#                     args: "*fragments.email_fragment"
#       validation: 
#         push:
#           - com.xyz.validateCreateUserArgs:
#       sync: 
#         REST: 
#           method_type: 'GET'
#         gRpc:
#       async:
#         messageBus:
#         socket:

#    com:
#     xyz:
#       helloWorld:
#         auths:
#           push:
#           - com.xyz.sendEmail:
#             args: "*fragments.email_fragment"
#             on_error:
#               - com.xyz.gs.retry:
#                   args:
#                     num_retry: 3
#                   on_error:
#                     - com.xyz.email_backlog:
#                       args: "*fragments.email_fragment"
#         validation: 
#           push:
#             - com.xyz.validateCreateUserArgs:                  
# export: 
#   com:
#    xyz:
#     helloWorld:

#       sync: 
#         REST: 
#           method_type: 'GET'
#         gRpc:
#       async:
#         messageBus:
#         socket:

#       deprecated: true
    
      



       
     
 
